# Generated by Django 6.0 on 2026-01-01 12:53

import apps.menu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menucategory_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.menu.models.product_photo_path, validators=[apps.menu.models.validate_image_file]),
        ),
    ]
