# Generated by Django 6.0 on 2026-01-01 12:53

import apps.accounts.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_secret_questions'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
    ]
