# Generated by Django 5.2.8 on 2026-01-01 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_managers'),
        ('accounts', '0004_update_secret_questions_texts'),
    ]

    operations = [
    ]
