# Generated by Django 5.2.8 on 2025-12-31 10:40

import apps.companies.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='company',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.companies.models.company_logo_path, validators=[apps.companies.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='CompanyWorkingHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Mon'), (1, 'Tue'), (2, 'Wed'), (3, 'Thu'), (4, 'Fri'), (5, 'Sat'), (6, 'Sun')])),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='companies.company')),
            ],
            options={
                'ordering': ['weekday'],
                'unique_together': {('company', 'weekday')},
            },
        ),
        migrations.DeleteModel(
            name='CompanyWorkingHours',
        ),
    ]
