# Generated by Django 6.0 on 2026-01-01 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_created_at_company_deleted_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyWorkingHour',
        ),
    ]
