# Generated by Django 5.2.8 on 2025-12-31 10:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_created_at_company_deleted_at_and_more'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipecomponent',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='recipecomponent',
            name='inventory_item',
        ),
        migrations.RemoveField(
            model_name='recipecomponent',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('company', 'name')},
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.DeleteModel(
            name='InventoryMovement',
        ),
        migrations.DeleteModel(
            name='RecipeComponent',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='min_quantity',
        ),
    ]
