# Generated by Django 5.2.8 on 2025-12-31 10:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_created_at_company_deleted_at_and_more'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emaillog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'ordering': ['code']},
        ),
        migrations.RemoveField(
            model_name='emaillog',
            name='receiver_user',
        ),
        migrations.RemoveField(
            model_name='emaillog',
            name='template',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='body',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='created_by',
        ),
        migrations.AddField(
            model_name='emaillog',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='companies.company'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='error_message',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='content',
            field=models.TextField(blank=True, default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='recipient',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('sent', 'sent'), ('failed', 'failed')], default='created', max_length=10),
        ),
    ]
